# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sglang_engine.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 0, "", "sglang_engine.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13sglang_engine.proto\x12\x10sglang.engine.v1"\x9d\x01\n\x0fGenerateRequest\x12\x19\n\x11request_json_body\x18\x01 \x01(\t\x12?\n\x07headers\x18\x02 \x03(\x0b\x32..sglang.engine.v1.GenerateRequest.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"C\n\x10GenerateResponse\x12\x1a\n\x12response_json_body\x18\x01 \x01(\t\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05"!\n\x0bTokenUpdate\x12\x12\n\njson_chunk\x18\x01 \x01(\t2\xbe\x01\n\x13SglangEngineService\x12Q\n\x08Generate\x12!.sglang.engine.v1.GenerateRequest\x1a".sglang.engine.v1.GenerateResponse\x12T\n\x0eGenerateStream\x12!.sglang.engine.v1.GenerateRequest\x1a\x1d.sglang.engine.v1.TokenUpdate0\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "sglang_engine_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_GENERATEREQUEST_HEADERSENTRY"]._loaded_options = None
    _globals["_GENERATEREQUEST_HEADERSENTRY"]._serialized_options = b"8\001"
    _globals["_GENERATEREQUEST"]._serialized_start = 42
    _globals["_GENERATEREQUEST"]._serialized_end = 199
    _globals["_GENERATEREQUEST_HEADERSENTRY"]._serialized_start = 153
    _globals["_GENERATEREQUEST_HEADERSENTRY"]._serialized_end = 199
    _globals["_GENERATERESPONSE"]._serialized_start = 201
    _globals["_GENERATERESPONSE"]._serialized_end = 268
    _globals["_TOKENUPDATE"]._serialized_start = 270
    _globals["_TOKENUPDATE"]._serialized_end = 303
    _globals["_SGLANGENGINESERVICE"]._serialized_start = 306
    _globals["_SGLANGENGINESERVICE"]._serialized_end = 496
# @@protoc_insertion_point(module_scope)
